### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by momalave** [xuxy09/RawSR#2]
I am trying to run inference/test, and get this error after executing "python train_and_test.py":

Traceback (most recent call last):
  File "train_and_test.py", line 1, in <module>
    from model import model
  File "/root/RawSR/model.py", line 7, in <module>
    from .parameters import GROWTH_RATE, KERNEL_SIZE_DENSE, BOTTLE_OUTPUT, LAYER_PER_BLOCK_DENSE, KERNEL_SIZE_NORMAL, \
ValueError: Attempted relative import in non-package

Any thoughts to fix this issue?

**Comment by momalave** [comment]
The problem has been fixed.

**Comment by momalave** [comment]
The issue has been fixed. I just removed the period before parameters in "from .parameters import ...".
